apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "plngxbackup.fullname" . }}"
data:
  backup.sh: |
    #!/bin/sh

    TIMESTAMP=$(date +"%Y%m%d-%H%M%S")

    echo "Creating paperless-ngx backup"
    kubectl exec {{ .Values.paperless.podname }} --container paperless-ngx -- \
      document_exporter \
      --no-progress-bar \
      --split-manifest \
      --use-folder-prefix \
      --zip \
      --zip-name "${TIMESTAMP}-plngx" \
      ../export

    # sleep infinity
