apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "plngxbackup.fullname" . }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ include "plngxbackup.fullname" . }}"
  template:
    metadata:
      name: "{{ include "plngxbackup.fullname" . }}"
      annotations:
        configmap-hash: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: "{{ include "plngxbackup.fullname" . }}"
    spec:
      serviceAccountName: {{ include "plngxbackup.fullname" . }}
      containers:
        - name: backup
          image: ghcr.io/taskmedia/kubectl-gpg-ftp:main
          command: ["sh", "-c", "sleep infinity"]
          # command: ["sh", "-c", "/scripts/backup.sh"]
          volumeMounts:
            - name: backup
              mountPath: /backup-plngx
            - name: script-volume
              mountPath: /scripts/backup.sh
              subPath: backup.sh
            {{- if .Values.encryption.enabled }}
            - name: gpg-volume
              mountPath: /scripts/publickey.gpg
              subPath: publickey.gpg
            {{- end }}
      restartPolicy: Always # TODO: change
      volumes:
        - name: backup
          emptyDir: {}
        - name: script-volume
          configMap:
            name: {{ include "plngxbackup.fullname" . }}
            items:
              - key: backup.sh
                path: backup.sh
            defaultMode: 0555 # read and execute
        {{- if .Values.encryption.enabled }}
        - name: gpg-volume
          configMap:
            name: {{ include "plngxbackup.fullname" . }}
            items:
              - key: publickey.gpg
                path: publickey.gpg
            defaultMode: 0444 # read only
        {{- end }}
