apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "plngxbackup.fullname" . }}"
subjects:
  - kind: ServiceAccount
    name: "{{ include "plngxbackup.fullname" . }}"
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: "{{ include "plngxbackup.fullname" . }}"
  apiGroup: rbac.authorization.k8s.io
